name = "allender_polylog_genus"
version = "0.1.0"
defaultTargets = ["Allender"]

[[lean_lib]]
name = "Allender"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.2"
